const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const store={},legacy={schemaVersion:3,namespace:'test',attempts:[{attemptId:'a-old',problemId:'P1',submittedAt:'2026-09-01T00:00:00.000Z',mode:'learning',correct:false}],reviewItems:[{reviewItemId:'r1',problemId:'P1',status:'pending',dueAt:'2026-09-02T00:00:00.000Z'}],sessions:{resume:{sessionId:'resume',problemId:'P1',status:'active'}},exposure:{P1:{status:'seen',firstSeenAt:'2026-09-01T00:00:00.000Z',lastSeenAt:'2026-09-01T00:00:00.000Z',source:'local'}},settings:{target:'safe'},device:{deviceId:'legacy-device',nickname:'My phone',lastSync:'2026-09-01T12:00:00.000Z'},createdAt:'2026-09-01T00:00:00.000Z'};
store['rikkyoMathFull:test:v3']=JSON.stringify(legacy);
global.window=global;global.location={search:'?env=test'};global.localStorage={getItem:k=>Object.prototype.hasOwnProperty.call(store,k)?store[k]:null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>{delete store[k]}};
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','src','schools','rikkyo','appProfile.js'),'utf8'));
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','storage.js'),'utf8'));
AppStorage.setKnownProblemIds(['P1','P2']);
assert.equal(AppStorage.migrationReport().status,'migrated');assert.equal(AppStorage.get().attempts.length,1);assert.equal(AppStorage.get().device.deviceId,'legacy-device');
assert.equal(AppStorage.get().device.nickname,'My phone');assert.equal(AppStorage.get().device.lastSync,'2026-09-01T12:00:00.000Z');
assert.ok(store['rikkyo-uk-math:test:learner-state:v1']);assert.ok(store['rikkyoMathFull:test:v3']);
const points=JSON.parse(store['rikkyo-uk-math:test:restore-points:v1']);assert.equal(points.length,1);assert.equal(points[0].snapshot.legacy,JSON.stringify(legacy));
assert.equal(AppStorage.activeSessions()[0].sessionId,'resume');assert.equal(AppStorage.get().settings.target,'safe');
const identities=AppStorage.identities();for(const value of Object.values(identities))assert.ok(!String(value).includes('waseshibu'));
assert.notEqual(identities.canonicalKey,identities.legacyKey);assert.equal(identities.indexedDbName,'rikkyo-uk-math-progress-sync');
const portable=JSON.parse(AppStorage.exportJson());assert.equal(portable.app,'rikkyo-uk-math');assert.equal(portable.backupSchemaVersion,1);assert.ok(!JSON.stringify(portable).includes('rikkyo-uk-math:test:device-id'));assert.equal(portable.learnerState.activityRecords[0].deviceId,'legacy-device');
const conflict=structuredClone(portable);conflict.learnerState.activityRecords[0].correct=true;delete conflict.checksum;
const fnv=str=>{let h=0x811c9dc5;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,0x01000193);}return (h>>>0).toString(16).padStart(8,'0')};conflict.checksum='fnv1a:'+fnv(JSON.stringify(conflict));
assert.throws(()=>AppStorage.importJson(JSON.stringify(conflict)),/activity conflict/);assert.equal(AppStorage.get().attempts[0].correct,false);
AppStorage.addAttempt({attemptId:'a-new',problemId:'P2',submittedAt:'2026-09-03T00:00:00.000Z',mode:'learning',correct:true});
assert.equal(JSON.parse(store['rikkyoMathFull:test:v3']).attempts.length,2);assert.equal(JSON.parse(store['rikkyo-uk-math:test:learner-state:v1']).activityRecords.length,2);
const missingProvenance=structuredClone(portable);delete missingProvenance.checksum;delete missingProvenance.learnerState.activityRecords[0].deviceId;missingProvenance.checksum='fnv1a:'+fnv(JSON.stringify(missingProvenance));
assert.throws(()=>AppStorage.importJson(JSON.stringify(missingProvenance)),/provenance missing/);
assert.throws(()=>AppStorage.importJson(JSON.stringify({schemaVersion:2,attempts:[{attemptId:'old-v2',problemId:'P1',submittedAt:'2026-01-01T00:00:00.000Z',mode:'learning'}],reviewItems:[],sessions:{},exposure:{},settings:{target:'stable'}})),/cannot be derived losslessly/);
const preferenceConflict=structuredClone(portable);delete preferenceConflict.checksum;preferenceConflict.learnerState.preferences.targetId='minimum';preferenceConflict.checksum='fnv1a:'+fnv(JSON.stringify(preferenceConflict));
assert.throws(()=>AppStorage.importJson(JSON.stringify(preferenceConflict)),/preferences conflict/);
const exposureConflict=structuredClone(portable);delete exposureConflict.checksum;exposureConflict.learnerState.exposureByProblemId.P1.source='other';exposureConflict.checksum='fnv1a:'+fnv(JSON.stringify(exposureConflict));
assert.throws(()=>AppStorage.importJson(JSON.stringify(exposureConflict)),/exposure conflict/);
console.log('PASS canonical migration: rehearsal, exact restore point, v3 shadow, post-write parity, no-loss conflict block, isolation');
