import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {assertExternalProgressSyncProfile} from '../src/engine/externalSyncContract.ts';
const context=vm.createContext({});for(const file of ['src/schools/rikkyo/syncProfile.js','src/schools/rikkyo/progressProjection.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context);
const p=context.RIKKYO_SYNC_PROFILE;assertExternalProgressSyncProfile(p);assert.equal(p.localDatabaseName,'rikkyo-uk-progress-sync');assert.equal(p.localDatabaseVersion,7);assert.equal(p.schoolId,'rikkyo-uk');assert.equal(p.projectionOwner,'school');
const at='2026-09-30T03:00:00.000Z',state={preferences:{targetId:'stable'},activityRecords:[{id:'a',problemId:'x',correct:false,examId:'R24-MATH-A',at,answer:'PRIVATE'}],sessionsById:{a:{examId:'R24-MATH-A',status:'finished',finishedAt:at,results:[{correct:true},{correct:false},{reviewRequired:true,correct:false}],answers:{raw:'PRIVATE'}},b:{examId:'R24-MATH-B',status:'active',startedAt:at}},reviewItems:[{status:'pending',reason:'retention'}],holdoutExamIds:['R26-MATH-B'],skillMetrics:[{state:'mastered'}]};
const before=JSON.stringify(state),rows=context.RIKKYO_MATH_PROGRESS_PROJECTION.buildStateRecords(state),get=id=>rows.find(x=>x.sourceRecordId===id).payload;
assert.equal(get('state:exam:FY24A').examStatus,'done');assert.equal(get('state:exam:FY24B').examStatus,'started');assert.equal(get('state:exam:FY26B').examStatus,'holdout');assert.equal(get('state:latest-exam').total,2);assert.equal(get('state:latest-exam').referenceAccuracy,50);assert.equal(get('state:latest-exam').score,undefined);assert.equal(get('state:summary').masteredCount,1);assert.equal(get('state:summary').lastLearningAt,at);assert.equal(JSON.stringify(state),before);assert.ok(!JSON.stringify(rows).includes('PRIVATE'));
state.holdoutExamIds=[];assert.equal(context.RIKKYO_MATH_PROGRESS_PROJECTION.buildStateRecords(state).find(x=>x.sourceRecordId==='state:exam:FY26B').payload.examStatus,'notstarted');
console.log('Math Cloud profile and projection PASS: actual external contract, A/B, policy holdout, excluded authority, privacy');
